# Generated by Django 3.0.7 on 2020-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('cover_letter', models.BooleanField(default=False)),
                ('followup', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
    ]
