# Generated by Django 3.0.7 on 2020-06-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cover_letter',
        ),
    ]
