# Generated by Django 3.0.7 on 2020-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200617_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='followup',
            field=models.BooleanField(default=False),
        ),
    ]
