# Generated by Django 3.0.7 on 2020-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_note_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Date posted'),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.CharField(choices=[('c', 'The job has been closed'), ('u', 'Update'), ('i', 'Important!!!'), ('p', 'Phone Screen'), ('f', 'Follow up')], default='c', max_length=2),
        ),
    ]
