# Generated by Django 3.0.7 on 2020-06-19 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200619_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 16, 17, 23, 290698, tzinfo=utc), verbose_name='Date applied'),
        ),
    ]
