# Generated by Django 3.0.7 on 2020-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200618_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='referral',
        ),
        migrations.AlterField(
            model_name='job',
            name='cover_letter',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.CharField(choices=[('u', 'Update'), ('i', 'Important!!!'), ('p', 'Phone Screen'), ('f', 'Follow up'), ('c', 'The job has been closed')], default='u', max_length=2),
        ),
    ]
