# Generated by Django 3.0.7 on 2020-06-20 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200620_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 15, 24, 40, 178478, tzinfo=utc), verbose_name='Date applied'),
        ),
    ]
