# Generated by Django 3.0.7 on 2020-06-20 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200620_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 20, 16, 7, 11, 245369, tzinfo=utc), verbose_name='Date applied'),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Job'),
        ),
    ]
