# Generated by Django 3.0.7 on 2020-06-23 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200620_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comment',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 23, 6, 41, 94386, tzinfo=utc), verbose_name='Date applied'),
        ),
    ]
