# Generated by Django 3.0.7 on 2020-06-18 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('cover_letter', models.CharField(max_length=750)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date posted')),
                ('comment', models.TextField(default='', max_length=250)),
                ('update', models.CharField(choices=[('u', 'Update'), ('!', 'Important!!!'), ('p', 'Phone Screen'), ('f', 'Follow up'), ('c', 'The job has been closed'), ('i', 'Interview')], default='u', max_length=2)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Job')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
