# Generated by Django 3.0.7 on 2020-06-19 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_job_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 15, 59, 55, 131535, tzinfo=utc), verbose_name='Date applied'),
        ),
    ]
